#import './UserCountersFragment.gql'
#import './UserInfoFragment.gql'

fragment MeUserFragment on User {
  email
  status
  ...UserInfoFragment
  ...UserCountersFragment

  location {
    country
    city
    coords {
      lat
      lng
    }
  }

  mapCenter {
    lat
    lng
  }
  mapZoom
  coords {
    lat
    lng
  }
}
