fragment PredictionsCardFragment on CachedPrediction {
  prediction
  predictionValue: prediction_value
  allVotesCount: all_votes_count
  agreedVotesPercent: agreed_votes_percent
  match {
    slug
    uniqueTournament: unique_tournament {
      name
    }
    matchDate: match_date
    country {
      iso
      name
    }
    teams {
      name
      logo
      slug
    }
  }
}
