query MapNearSearch($lat: Float!, $lng: Float!, $distance: Int!) {
  searchNearPlace(input: { lat: $lat, lng: $lng, distance: $distance}) {
    slug
    name
    geometry {
      viewport {
        northeast {
          lat
          lng
        }
        southwest {
          lat
          lng
        }
      }
      location {
        lat
        lng
      }
    }
    rating {
      value
      count
    }
    address
  }
}
