mutation RegisterUser($email: String!, $userName: String!, $token: String!, $firstName: String, $lastName: String) {
  register(input: { email: $email, token: $token, userName: $userName, firstName: $firstName, lastName: $lastName }) {
    userName
    firstName
    lastName
    email
    status
    token
  }
}
