mutation RegisterUser($email: String!, $username: String!, $token: String!, $firstName: String!, $lastName: String) {
  register(input: { email: $email, token: $token, userName: $username, firstName: $firstName, lastName: $lastName }) {
    userName
    firstName
    lastName
    email
    status
    token
  }
}
