query SearchPlaces($term: String!, $bbox: String) {
  searchPlace(input: { search: $term, bbox: $bbox }) {
    slug
    name
    geometry {
      viewport {
        northeast {
          lat
          lng
        }
        southwest {
          lat
          lng
        }
      }
      location {
        lat
        lng
      }
    }
    rating {
      value
      count
    }
    address
  }
}
