mutation EditUser($userName: String, $firstName: String, $lastName: String, $bio: String, $token: String!) {
  editUser(input: { userName: $userName, firstName: $firstName, lastName: $lastName, bio: $bio, token: $token }) {
    userName
  }
}
